core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('select2/', include('django_select2.urls')),
]

home/urls.py
from home import apps
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('register/', views.register, name="register"),
    path('management/', views.management, name="management-default"),
    path('management/<str:menu_item>/',
         views.management_content_view, name='management'),

    path('units/', views.unit_list, name='unit_list'),
    path('units/create/', views.unit_create, name='unit_create'),
    path('units/update/<int:pk>/', views.unit_update, name='unit_update'),
    path('units/delete/<int:pk>/', views.unit_delete, name='unit_delete'),

    path('departments/', views.department_list, name='department_list'),
    path('departments/create/', views.department_create, name='department_create'),
    path('departments/update/<int:pk>/',
         views.department_update, name='department_update'),
    path('departments/delete/<int:pk>/',
         views.department_delete, name='department_delete'),

    path('positions/', views.position_list, name='position_list'),
    path('positions/create/', views.position_create, name='position_create'),
    path('positions/update/<int:pk>/',
         views.position_update, name='position_update'),
    path('positions/delete/<int:pk>/',
         views.position_delete, name='position_delete'),

    path('items/', views.item_list, name='item_list'),
    path('items/create/', views.item_create, name='item_create'),
    path('items/update/<int:pk>/',
         views.item_update, name='item_update'),
    path('items/delete/<int:pk>/',
         views.item_delete, name='item_delete'),

    path('faculties/', views.faculty_list, name='faculty_list'),
    #     path('faculties/create/', views.faculty_create_or_update, name='faculty_create'),
    path('faculties/create/', views.faculty_create, name='faculty_create'),
    #     path('faculties/update/<int:pk>/',
    #          views.faculty_create_or_update, name='faculty_update'),
    path('faculties/update/<int:pk>/',
         views.faculty_update, name='faculty_update'),
    path('faculties/delete/<int:pk>/',
         views.faculty_delete, name='faculty_delete'),


    path('get-status-counts/', views.get_status_counts, name='get_status_counts'),
    path('get-gender-counts/', views.get_gender_counts, name='get_gender_counts'),
    path('get-item-status-counts-per-year/', views.get_item_status_counts_per_year,
         name='get_item_status_counts_per_year'),
    path('get-position-counts/', views.get_position_counts,
         name='get_position_counts'),
    path('get-item-status-counts/', views.get_item_status_counts,
         name='get_item_status_counts'),

    # dashboard tiles
    path('faculty-counts/', views.faculty_counts, name='faculty_counts'),
    path('faculty-education-counts/', views.faculty_education_counts,
         name='faculty_education_counts'),
    path('faculty-status-counts/', views.faculty_status_counts,
         name='faculty_status_counts'),
    path('faculty-type-counts/', views.faculty_type_counts,
         name='faculty_type_counts'),
    path('faculty-gender-itemstatus-counts/', views.faculty_gender_itemstatus_counts,
         name='faculty_gender_itemstatus_counts'), \

    # reports
    path('generate-faculty-pdf/', views.generate_faculty_pdf,
         name='generate_faculty_pdf'),
    path('generate-faculty-education-pdf/', views.generate_faculty_education_pdf,
         name='generate_faculty_education_pdf'),
    path('generate-faculty-type-pdf/', views.generate_faculty_type_pdf,
         name='generate_faculty_type_pdf'),
    path('generate-faculty-status-pdf/', views.generate_faculty_item_status_pdf,
         name='generate_faculty_status_pdf'),

    # charts/reports
    path('unit-report-html', views.unit_chart_html,
         name='unit_chart_html'),
    path('unit-admin-report-html', views.unit_admin_chart_html,
         name='unit_admin_chart_html'),
    path('unit-report-list/<int:flag>/', views.get_faculty_list,
         name='unit_chart_list'),
    path('unit-report-chart/<int:flag>/', views.unit_chart_data,
         name='unit_chart_unit'),
    path('admin-report-chart/', views.admin_report_chart,
         name='admin_chart_unit'),

    # aplha list
    path('alpha-list-report/', views.employee_alpha_list,
         name='employee_alpha_list'),

    # graphs
    path('generate-status-pdf/', views.generate_status_graph_pdf,
         name='generate_status_chart_pdf'),
]

templates/reports/chart_admin_report.html
{% extends "base.html" %}

{% block title %}HR Dashboard{% endblock %}

{% block content %}
<div class="row mt-2">
    <div class="col-md-6">
        <div class="card mb-2">
            <div class="card-header bg-success text-white">
                <div class="d-flex justify-content-between align-items-center">
                    <span>Non-Academic Unit Line Chart</span>
                    <span class="ms-auto"><a href="#" id="downloadLineChartPdf" class="btn btn-sm btn-warning">Report (Pdf)</a></span> | 
                    <select id="item-status-year-select" name="year_line" class="form-select w-auto" hx-get="{% url 'home:get_item_status_counts_per_year' %}" hx-trigger="change" hx-target="#item-status-chart-data" hx-include="[name='year_line']">
                        <option value="">Select Year</option>
                        <!-- Options will be dynamically generated -->
                    </select>
                </div>
            </div>
            <div class="card-body" id="itemStatusChartContainer">
                <canvas id="itemStatusChart"></canvas>
                <div id="item-status-chart-data" hx-swap="outerHTML:swap"></div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card mb-2">
            <div class="card-header bg-success text-white">
                <div class="d-flex justify-content-between align-items-center">
                    <span>Non-Academic Unit Bar Chart</span> 
                    <span class="ms-auto"><a href="#" id="downloadBarChartPdf" class="btn btn-sm btn-warning">Report (Pdf)</a></span> | 
                    {% comment %} <a href="{% url 'home:generate_status_chart_pdf' %}" class="btn btn-sm btn-warning w-auto">Report (Pdf)</a> {% endcomment %}
                    <select id="year-select" name="year_bar" class="form-select w-auto" hx-get="{% url 'home:get_status_counts' %}" hx-target="#chart-data" hx-trigger="change" hx-include="[name='year_bar']">
                        <option value="">All years</option>
                    </select>
                </div>
            </div>
            <div class="card-body" id="statusBarChar">
                <canvas id="statusChart"></canvas>
                <div id="chart-data" hx-swap="outerHTML:swap"></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/reports/chart_unit_admin_report.html
{% extends "base.html" %}

{% block title %}Admin Dashboard{% endblock %}

{% block content %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>

<h3>Administrative Units</h3>
<div class="row mt-2">
    <div class="col-md-12">
        <div class="card mb-2">
            <div class="card-header bg-success text-white">
                <div class="d-flex justify-content-end align-items-center">

                    <label for="year-select" class="form-label me-2">Select Year</label>
                    <select id="year-select" name="year_position" class="form-select w-25 me-4" hx-get="{% url 'home:unit_chart_list' 2 %}" hx-target="#unit-chart-data" hx-trigger="change, load" hx-include="[name='year_position'], [name='unit_id']" hx-target="#faculty-table-body" hx-swap="outerHTML">>
                        <option value="">All Years</option>
                        {% for year in years %}
                            <option value="{{ year.year }}">{{ year.year }}</option>
                        {% endfor %}
                    </select>
                    <label for="unit-select" class="form-label me-2">Select Unit</label>
                    <select id="unit-select" name="unit_id" class="form-select w-25" hx-get="{% url 'home:unit_chart_list' 2 %}" hx-target="#unit-chart-data" hx-trigger="change, load" hx-include="[name='year_position'], [name='unit_id']" hx-target="#faculty-table-body" hx-swap="outerHTML">>
                        <option value="">All Units</option>
                        {% for unit in units %}
                            <option value="{{ unit.id }}">{{ unit.unit_name }}</option>
                        {% endfor %}
                    </select>
                    <span class="ms-auto"><a href="#" id="downloadPdf" class="btn btn-sm btn-warning">Report (Pdf)</a></span>
                </div>
            </div>
            
            <div id="administrative-chart">
                <div class="row p-4">
                    <div class="col-md-8">
                        <div class="card-body" id="academic-unit-line-chart-container">
                            <div class="text-center"><h5>Administrative Position Distribution</h5></div>
                            <canvas id="positionChart"></canvas>
                            <!-- <div id="unit-chart-data" hx-swap="outerHTML:swap" class="invisible"></div> -->
                        </div>
                    </div>
        
                    <div class="col-md-4">
                        <div class="card-body" id="academic-unit-line-chart-container-pie">
                            <div class="text-center"><h5>Administrative Position Pie Chart</h5></div>
                            <canvas id="positionChartPie"></canvas>
                            <!-- <div id="unit-chart-data" hx-swap="outerHTML:swap" class="invisible"></div> -->
                        </div>
                    </div>

                    <div class="col-md-12">
                        <h5 class="mt-5 mp-4">Position Counts</h5>
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Position</th>
                                    <th class="text-end">Count</th>
                                </tr>
                            </thead>
                            <tbody id="position-counts-table">
                                <!-- Position count rows will be dynamically inserted here -->
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row mt-4">
    <div class="col-md-12">
        <h5>List of Faculty</h5> 
        <table class="table table-striped table-bordered table-hover" id="faculty-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Faculty No</th>
                    <th>Item No</th>
                    <th>Name</th>
                    <th>Position</th>
                    <th>Gender</th>
                    <th>Item Status</th>
                    <th>Department Name</th>
                </tr>
            </thead>
            <tbody id="faculty-table-body">
                <!-- Dynamic rows will be inserted here -->
            </tbody>
        </table>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const ctx = document.getElementById('positionChart').getContext('2d');
        const positionChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: [],
                datasets: []
            },
            options: {
                responsive: true,
                scales: {
                    y: {
                        beginAtZero: true
                    }
                },
                plugins: {
                    legend: {
                        display: false
                    }
                }
            }
        });

        const ctx1 = document.getElementById('positionChartPie').getContext('2d');
        const positionChartPie = new Chart(ctx1, {
            type: 'pie',
            data: {
                labels: [],
                datasets: []
            },
            options: {
                responsive: true,
                scales: {
                    y: {
                        beginAtZero: true
                    }
                },
                plugins: {
                    legend: {
                        display: false
                    }
                }
            }
        });

        // Function to generate a random color
        function getRandomColor() {
            const r = Math.floor(Math.random() * 255);
            const g = Math.floor(Math.random() * 255);
            const b = Math.floor(Math.random() * 255);
            return `rgba(${r}, ${g}, ${b}, 0.2)`;
        }

        // Function to generate a random border color
        function getRandomBorderColor() {
            const r = Math.floor(Math.random() * 255);
            const g = Math.floor(Math.random() * 255);
            const b = Math.floor(Math.random() * 255);
            return `rgba(${r}, ${g}, ${b}, 1)`;
        }

        function updateChart(chart, chart1, data) {
            const labels = data.positions;
            const counts = data.counts;

            const backgroundColors = labels.map(() => getRandomColor());
            const borderColors = labels.map(() => getRandomBorderColor());

            chart.data.labels = labels;
            chart.data.datasets = [{
                label: 'Position Count',
                data: counts,
                backgroundColor: backgroundColors,
                borderColor: borderColors,
                borderWidth: 1
            }];
            chart.update();

            chart1.data.labels = labels;
            chart1.data.datasets = [{
                label: 'Position Count',
                data: counts,
                backgroundColor: backgroundColors,
                borderColor: borderColors,
                borderWidth: 1
            }];
            chart1.update();

            // Update the position counts table
            const positionCountsTable = document.getElementById('position-counts-table');
            positionCountsTable.innerHTML = ''; // Clear existing table rows

            labels.forEach((label, index) => {
                const row = document.createElement('tr');
                row.innerHTML = `<td>${label}</td><td class="text-end">${counts[index]}</td>`;
                positionCountsTable.appendChild(row);
            });
        }

        document.querySelectorAll('#year-select, #unit-select').forEach(selectElement => {
            selectElement.addEventListener('change', function(evt) {
                const year = document.getElementById('year-select').value;
                const unit = document.getElementById('unit-select').value;
                fetch(`{% url 'home:unit_chart_unit' 2 %}?year_position=${year}&unit_id=${unit}`)
                    .then(response => response.json())
                    .then(data => {
                        updateChart(positionChart, positionChartPie, data);
                    });
                fetch(`{% url 'home:unit_chart_list' 2 %}?year_position=${year}&unit_id=${unit}`)
                    .then(response => response.json())
                    .then(data => {
                        const tbody = document.getElementById('faculty-table-body');
                        tbody.innerHTML = '';
                        let counter = 1;
                        data.faculty.forEach(faculty => {
                            const itemStatusClass = faculty.item_status === 'COS' ? 'bg-danger' :
                                                    faculty.item_status === 'Vacant' ? 'bg-primary' :
                                                    faculty.item_status === 'JO' ? 'bg-warning' : 'bg-success';
                            const row = document.createElement('tr');
                            row.innerHTML = `
                                <td>${counter++}</td>
                                <td>${faculty.faculty_no}</td>
                                <td>${faculty.item_no}</td>
                                <td>${faculty.name}</td>
                                <td>${faculty.position}</td>
                                <td>${faculty.gender}</td>
                                <td><span class="badge rounded-pill ${itemStatusClass}">${faculty.item_status}</span></td>
                                <td>${faculty.department_name}</td>
                            `;
                            tbody.appendChild(row);
                        });
                    });
            });

            // Load initial data for all years and units
            fetch("{% url 'home:unit_chart_unit' 2 %}")
                .then(response => response.json())
                .then(data => {
                    updateChart(positionChart, positionChartPie, data);
                });

            document.getElementById('downloadPdf').addEventListener('click', function() {
                const chartContainer = document.querySelector('#administrative-chart');
                const facultyTable = document.querySelector('.table');

                html2canvas(chartContainer).then(canvas => {
                    const imgDataChart = canvas.toDataURL('image/png');
                    const { jsPDF } = window.jspdf;
                    const pdf = new jsPDF();

                    pdf.addImage(imgDataChart, 'PNG', 15, 15, 180, 160);

                    html2canvas(facultyTable).then(canvasTable => {
                        const imgDataTable = canvasTable.toDataURL('image/png');
                        pdf.addPage();
                        pdf.addImage(imgDataTable, 'PNG', 10, 10, 190, 0);
                        pdf.save('status_report.pdf');
                    });
                });
            });
        });

        // $(document).ready(function() {
        //    $('#faculty-table').DataTable();
        // });
    });
</script>

{% endblock %}

templates/reports/chart_unit_report.html
{% extends "base.html" %}

{% block title %}Admin Dashboard{% endblock %}

{% block content %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>

<h3>Academic Units</h3>
<div class="row mt-2">
    <div class="col-md-12">
        <div class="card mb-2">
            
            <div class="card-header bg-success text-white">
                <div class="d-flex justify-content-end align-items-center">

                    <label for="year-select" class="form-label me-2">Select Year</label>
                    <select id="year-select" name="year_position" class="form-select w-25 me-4" hx-get="{% url 'home:unit_chart_list' 1 %}" hx-target="#unit-chart-data" hx-trigger="change, load" hx-include="[name='year_position'], [name='unit_id']" hx-target="#faculty-table-body" hx-swap="outerHTML">>
                        <option value="">All Years</option>
                        {% for year in years %}
                            <option value="{{ year.year }}">{{ year.year }}</option>
                        {% endfor %}
                    </select>
                    <label for="unit-select" class="form-label me-2">Select Unit</label>
                    <select id="unit-select" name="unit_id" class="form-select w-25" hx-get="{% url 'home:unit_chart_list' 1 %}" hx-target="#unit-chart-data" hx-trigger="change, load" hx-include="[name='year_position'], [name='unit_id']" hx-target="#faculty-table-body" hx-swap="outerHTML">>
                        <option value="">All Units</option>
                        {% for unit in units %}
                            <option value="{{ unit.id }}">{{ unit.unit_name }}</option>
                        {% endfor %}
                    </select>
                    <span class="ms-auto"><a href="#" id="downloadPdf" class="btn btn-sm btn-warning">Report (Pdf)</a></span>
                </div>
            </div>
            
            <div id="academic-chart">
                <div class="row p-4">
                    <div class="col-md-8">
                        <div class="card-body" id="academic-unit-line-chart-container">
                            <div class="text-center"><h5>Faculty Position Distribution</h5></div>
                            <canvas id="positionChart"></canvas>
                            <!-- <div id="unit-chart-data" hx-swap="outerHTML:swap" class="invisible"></div> -->
                        </div>
                    </div>
        
                    <div class="col-md-4">
                        <div class="card-body" id="academic-unit-line-chart-container-pie">
                            <div class="text-center"><h5>Faculty Position Pie Chart</h5></div>
                            <canvas id="positionChartPie"></canvas>
                            <!-- <div id="unit-chart-data" hx-swap="outerHTML:swap" class="invisible"></div> -->
                        </div>
                    </div>

                    <div class="col-md-12">
                        <h5 class="mt-5 mp-4">Position Counts</h5>
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Position</th>
                                    <th class="text-end">Count</th>
                                </tr>
                            </thead>
                            <tbody id="position-counts-table">
                                <!-- Position count rows will be dynamically inserted here -->
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row mt-4">
    <div class="col-md-12">
        <h5>List of Faculty</h5> 
        <table class="table table-striped table-bordered table-hover" id="faculty-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Faculty No</th>
                    <th>Item No</th>
                    <th>Name</th>
                    <th>Position</th>
                    <th>Gender</th>
                    <th>Item Status</th>
                    <th>Department Name</th>
                </tr>
            </thead>
            <tbody id="faculty-table-body">
                <!-- Dynamic rows will be inserted here -->
            </tbody>
        </table>
    </div>
</div>


<script>
    document.addEventListener('DOMContentLoaded', function() {
        const ctx = document.getElementById('positionChart').getContext('2d');
        const positionChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: [],
                datasets: []
            },
            options: {
                responsive: true,
                scales: {
                    y: {
                        beginAtZero: true
                    }
                },
                plugins: {
                    legend: {
                        display: false
                    }
                }
            }
        });

        const ctx1 = document.getElementById('positionChartPie').getContext('2d');
        const positionChartPie = new Chart(ctx1, {
            type: 'pie',
            data: {
                labels: [],
                datasets: []
            },
            options: {
                responsive: true,
                scales: {
                    y: {
                        beginAtZero: true
                    }
                },
                plugins: {
                    legend: {
                        display: false
                    }
                }
            }
        });

        // Function to generate a random color
        function getRandomColor() {
            const r = Math.floor(Math.random() * 255);
            const g = Math.floor(Math.random() * 255);
            const b = Math.floor(Math.random() * 255);
            return `rgba(${r}, ${g}, ${b}, 0.2)`;
        }

        // Function to generate a random border color
        function getRandomBorderColor() {
            const r = Math.floor(Math.random() * 255);
            const g = Math.floor(Math.random() * 255);
            const b = Math.floor(Math.random() * 255);
            return `rgba(${r}, ${g}, ${b}, 1)`;
        }

        function updateChart(chart, chart1, data) {
            const labels = data.positions;
            const counts = data.counts;

            const backgroundColors = labels.map(() => getRandomColor());
            const borderColors = labels.map(() => getRandomBorderColor());

            chart.data.labels = labels;
            chart.data.datasets = [{
                label: 'Position Count',
                data: counts,
                backgroundColor: backgroundColors,
                borderColor: borderColors,
                borderWidth: 1
            }];
            chart.update();

            chart1.data.labels = labels;
            chart1.data.datasets = [{
                label: 'Position Count',
                data: counts,
                backgroundColor: backgroundColors,
                borderColor: borderColors,
                borderWidth: 1
            }];
            chart1.update();

            // Update the position counts table
            const positionCountsTable = document.getElementById('position-counts-table');
            positionCountsTable.innerHTML = ''; // Clear existing table rows

            labels.forEach((label, index) => {
                const row = document.createElement('tr');
                row.innerHTML = `<td>${label}</td><td class="text-end">${counts[index]}</td>`;
                positionCountsTable.appendChild(row);
            });
        }

        document.querySelectorAll('#year-select, #unit-select').forEach(selectElement => {
            selectElement.addEventListener('change', function(evt) {
                const year = document.getElementById('year-select').value;
                const unit = document.getElementById('unit-select').value;
                fetch(`{% url 'home:unit_chart_unit' 1 %}?year_position=${year}&unit_id=${unit}`)
                    .then(response => response.json())
                    .then(data => {
                        updateChart(positionChart, positionChartPie, data);
                    });
                fetch(`{% url 'home:unit_chart_list' 1 %}?year_position=${year}&unit_id=${unit}`)
                    .then(response => response.json())
                    .then(data => {
                        const tbody = document.getElementById('faculty-table-body');
                        tbody.innerHTML = '';
                        let counter = 1;
                        data.faculty.forEach(faculty => {
                            const itemStatusClass = faculty.item_status === 'COS' ? 'bg-danger' :
                                                    faculty.item_status === 'Vacant' ? 'bg-primary' :
                                                    faculty.item_status === 'JO' ? 'bg-warning' : 'bg-success';
                            const row = document.createElement('tr');
                            row.innerHTML = `
                                <td>${counter++}</td>
                                <td>${faculty.faculty_no}</td>
                                <td>${faculty.item_no}</td>
                                <td>${faculty.name}</td>
                                <td>${faculty.position}</td>
                                <td>${faculty.gender}</td>
                                <td><span class="badge rounded-pill ${itemStatusClass}">${faculty.item_status}</span></td>
                                <td>${faculty.department_name}</td>
                            `;
                            tbody.appendChild(row);
                        });
                    });
            });

            // Load initial data for all years and units
            fetch("{% url 'home:unit_chart_unit' 1 %}")
                .then(response => response.json())
                .then(data => {
                    updateChart(positionChart, positionChartPie, data);
                });

            document.getElementById('downloadPdf').addEventListener('click', function() {
                const chartContainer = document.querySelector('#academic-chart');
                // const facultyTable = document.querySelector('.table');
                const facultyTable = document.querySelector('#faculty-table');

                html2canvas(chartContainer).then(canvas => {
                    const imgDataChart = canvas.toDataURL('image/png');
                    const { jsPDF } = window.jspdf;
                    const pdf = new jsPDF();

                    pdf.addImage(imgDataChart, 'PNG', 20, 20, 160, 160);

                    html2canvas(facultyTable).then(canvasTable => {
                        const imgDataTable = canvasTable.toDataURL('image/png');
                        pdf.addPage();
                        pdf.addImage(imgDataTable, 'PNG', 10, 10, 190, 0);
                        pdf.save('status_report.pdf');
                    });
                });
            });

        });

        // $(document).ready(function() {
        //     $('#faculty-table').DataTable();
        // });
    
    });

    
</script>

{% endblock %}

templates/reports/partial_alpha_list.html
<!-- partials/faculty_table.html -->
<tbody>
    {% for employee in employees %}
        <tr>
            <td>{{employee.faculty_no}}</td>
            <td>{{employee}}</td>
            <td>{{employee.item_no}}</td>
            <td>{{employee.position_id}}</td>
            <td>{{employee.gender}}</td>
            <td>{{employee.education}}</td>
            <td>{{employee.date_hired|date:"Y-m-d"}}</td>
            <td>{{employee.email_address}}</td>
            <td>{{employee.employment_type}}</td>
            <td>{{employee.item_status}}</td>
            <td>{{employee.department_id}}</td>
        </tr>
    {% endfor %}
</tbody>